contacts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contacts/', views.Contacts.as_view(), name='contacts'),
    path('success/', views.Success.as_view()),
]

dp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('__debug__/', include('debug_toolbar.urls')),
    path('', include('welcome.urls')),
    path('', include('contacts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

welcome/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MainPage.as_view(), name='mp'),
    path('band/', views.BandView.as_view(), name='bnd'),
    path('discography/', views.DiscographyView.as_view(), name='dsc'),
    path('bio/', views.DPBio.as_view(), name='bio'),
    path('discography/<slug:slug>/', views.AlbumView.as_view(), name='alb'),
    path('gallery/', views.GalleryView.as_view(), name='gallery'),
]

contacts/models.py
from django.core.validators import MinLengthValidator
from django.db import models


class ContactModel(models.Model):
    name = models.CharField(max_length=20, null=False, validators=[MinLengthValidator(3)])
    e_mail = models.EmailField(default='')
    message = models.TextField(max_length=180, null=False)

welcome/models.py
from django.db import models
from django.utils.text import slugify
from django.core.validators import MinValueValidator, MaxValueValidator


class Band(models.Model):
    name = models.CharField(max_length=100)
    instrument = models.CharField(max_length=100)
    site = models.URLField(default='')
    slug = models.SlugField(default='', null=False, db_index=True)
    portrait = models.ImageField(upload_to='portraits', default='')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Band, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


# one to many
class Mark(models.Model):
    BAND_MEMBERS_CHOICES = [
        ('RE', 'Rod Evans'),
        ('IG', 'Ian Gillan'),
        ('DC', 'David Coverdale'),
        ('JLT', 'Joe Lynn Turner'),
        ('RB', 'Ritchie Blackmore'),
        ('TB', 'Tommy Bolin'),
        ('JS', 'Joe Satriani'),
        ('SM', 'Steve Morse'),
        ('SMB', 'Simon McBride'),
        ('NS', 'Nick Simper'),
        ('RG', 'Roger Glover'),
        ('GH', 'Glenn Hughes'),
        ('JL', 'Jon Lord'),
        ('DA', 'Don Airey'),
        ('IP', 'Ian Paice'),
    ]
    number = models.CharField(max_length=5)
    vocals = models.CharField(max_length=3, choices=BAND_MEMBERS_CHOICES, default='IG')
    guitar = models.CharField(max_length=3, choices=BAND_MEMBERS_CHOICES, default='RB')
    keyboards = models.CharField(max_length=3, choices=BAND_MEMBERS_CHOICES, default='JL')
    bass = models.CharField(max_length=3, choices=BAND_MEMBERS_CHOICES, default='RG')
    drums = models.CharField(max_length=3, choices=BAND_MEMBERS_CHOICES, default='IP')
    mark_foto = models.ImageField(upload_to='mark_foto', default='')

    def __str__(self):
        return f'Mark {self.number}'


# альбом
class Discography(models.Model):
    album_title = models.CharField(max_length=100)
    album_year = models.IntegerField(validators=[MinValueValidator(1968), MaxValueValidator(2023)])
    mark = models.ForeignKey(Mark, on_delete=models.SET_NULL, related_name='albums', null=True)
    slug = models.SlugField(default='', null=False, db_index=True)
    cover = models.ImageField(upload_to='covers', default='')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.album_title)
        super(Discography, self).save(*args, **kwargs)

    def __str__(self):
        return self.album_title


# песни из альбома
class Albums(models.Model):
    album = models.ForeignKey(Discography, on_delete=models.SET_NULL, related_name='songs', null=True)
    song_number = models.IntegerField()
    song_title = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.song_title)
        super(Albums, self).save(*args, **kwargs)

    def __str__(self):
        return self.song_title


class Bio(models.Model):
    dp_bio = models.TextField(default='')

    def __str__(self):
        return 'About Deep Purple'

contacts/forms.py
from django import forms
from contacts.models import ContactModel


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = '__all__'
        labels = {
            'name': 'Name:',
            'e_mail': 'E-mail:',
            'message': 'Message:'
        }

contacts/views.py
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse
from django.views.generic import TemplateView, FormView
from contacts.forms import ContactForm


class Success(TemplateView):
    template_name = 'contacts/success.html'


class Contacts(FormView):
    form_class = ContactForm
    success_url = '/success/'
    template_name = 'contacts/contacts.html'

    def form_valid(self, form):
        form.save()
        try:
            send_mail(
                subject='New message from your Deep Purple website user form',
                message=f'''
                Name: {form.cleaned_data['name']}\n\n
                E-mail: {form.cleaned_data['e_mail']}\n\n
                Message: {form.cleaned_data['message']}\n
                ''',
                from_email='infodjango47@gmail.com',
                recipient_list=['pavelcyargeenka@gmail.com'],
                fail_silently=True
            )

            send_mail(
                subject='This is an automatically generated email – please do not reply to it',
                message=f'Thank you for your message! We will contact you as soon as possible.\n\n',
                from_email='infodjango47@gmail.com',
                recipient_list=[form.cleaned_data['e_mail']],
                fail_silently=True
            )

        except BadHeaderError:
            return HttpResponse('Invalid header found')
        return super(Contacts, self).form_valid(form)

welcome/views.py
from welcome.models import Band, Discography, Mark, Bio
from django.views.generic import TemplateView, ListView, DetailView


class MainPage(TemplateView):
    template_name = 'welcome/welcome.html'


class BandView(ListView):
    model = Band
    template_name = 'welcome/band.html'
    context_object_name = 'members'


class DiscographyView(ListView):
    model = Discography
    template_name = 'welcome/discography.html'
    context_object_name = 'band_discography'

    def get_queryset(self):
        super(DiscographyView, self).get_queryset()
        qs_sorted = Discography.objects.order_by('album_year')
        return qs_sorted


class DPBio(TemplateView):
    template_name = 'welcome/bio.html'

    def get_context_data(self, **kwargs):
        context = super(DPBio, self).get_context_data()
        context['dp_bio'] = Bio.objects.get(id=1)
        return context


class AlbumView(DetailView):
    model = Discography
    template_name = 'welcome/album.html'
    context_object_name = 'this_album'


class GalleryView(ListView):
    model = Mark
    template_name = 'welcome/gallery.html'
    context_object_name = 'line_ups'

contacts/templates/contacts/contacts.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'contacts/css/contacts.css' %}" >
{% endblock %}

{% block title %} Contact me {% endblock %}

{% block content %}

{% include 'welcome/navbar_welcome.html' %}
<h3>Contact me!</h3>

<div class="form">
    <form method="post" target="_self">
    {% csrf_token %}
    {% for field in form %}
    <div class="fields">
        {{ field.errors }}
        {{ field.label_tag }} <br>
        {{ field }}
    </div>
    {% endfor %}
    <input type='submit' value="Submit!">
    </form>
</div>

{% endblock %}

contacts/templates/contacts/success.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'contacts/css/contacts.css' %}" >
{% endblock %}

{% block title %} Thanks! {% endblock %}

{% block content %}
{% include 'welcome/navbar_welcome.html' %}<br>
<h3>Thank you! Your message has been successfully sent!</h3>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block css %}{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %} {% endblock %}
</body>
</html>

welcome/templates/welcome/album.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'welcome/css/album.css' %}" >
{% endblock %}

{% block title %}{{this_album.album_title}}{% endblock %}

{% block content %}

{% include 'welcome/navbar_welcome.html' %}
<h2>{{this_album.album_title}} ({{this_album.album_year}})</h2>
<img src="{{this_album.cover.url}}" width="400" height="400">

<table>
    {% for song in this_album.songs.all %}
    <tr>
        <td>{{song.song_number}}.</td>
        <td>{{song.song_title}}</td>
    </tr>
    {% endfor %}
</table><br><br>

<table>
    <tr><td>{{this_album.mark.get_vocals_display|upper}} - vocals</td></tr>
    <tr><td>{{this_album.mark.get_guitar_display|upper}} - guitar</td></tr>
    <tr><td>{{this_album.mark.get_keyboards_display|upper}} - keyboards</td></tr>
    <tr><td>{{this_album.mark.get_drums_display|upper}} - drums</td></tr>
    {% if this_album.mark.bass == 'GH' %}
        <tr><td>{{this_album.mark.get_bass_display|upper}} - bass, vocals</td></tr>
    {% else %}
        <tr><td>{{this_album.mark.get_bass_display|upper}} - bass</td></tr>
    {% endif %}
</table><br><br>
{% endblock %}

welcome/templates/welcome/band.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'welcome/css/band.css' %}" />
{% endblock %}

{% block title %} Band {% endblock %}

{% block content %}
{% include 'welcome/navbar_welcome.html' %}

<h1>THE BAND</h1>

{% for member in members %}
<div class="images">
  <a class="site" href="{{member.site}}">
    <figure>
      <img
        src="{{member.portrait.url}}"
        alt="DP member"
        width="150"
        height="150"
      />
      <figcaption class="figcap">{{member.name}}</figcaption>
    </figure>
  </a>
</div>
{% endfor %}
{% endblock %}

welcome/templates/welcome/bio.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'welcome/css/bio.css' %}" />
{% endblock %}

{% block title %} Bio {% endblock %}

{% block content %}
{% include 'welcome/navbar_welcome.html' %}

<img src="{% static 'welcome/img/bioo.jpg'%}" width="400" height="370" />

{% autoescape off %} <!-- to applicate html tags -->
{{dp_bio.dp_bio}}
{% endautoescape %}

{% endblock %}

welcome/templates/welcome/discography.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'welcome/css/discography.css' %}" >
{% endblock %}

{% block title %} Discography {% endblock %}

{% block content %}

{% include 'welcome/navbar_welcome.html' %}
<h1>DISCOGRAPHY</h1>

{% for album in band_discography %}
<div class="covers">
   <a class="album" href="{% url 'alb' slug=album.slug %}">
    <figure>
      <img src="{{album.cover.url}}" width="200" height="200">
      <figcaption>{{album.album_title}} ({{album.album_year}})</figcaption>
    </figure>
   </a>
</div>
{% endfor %}

{% endblock %}

welcome/templates/welcome/gallery.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'welcome/css/gallery.css' %}" >
{% endblock %}

{% block title %} Gallery {% endblock %}

{% block content %}
{% include 'welcome/navbar_welcome.html' %}

{% for line_up in line_ups %}
<div class="mark"><h2>MARK {{line_up.number}}:</h2></div>
<ul class="m">
    <li>{{line_up.get_vocals_display|upper}}</li>
    <li>{{line_up.get_guitar_display|upper}}</li>
    <li>{{line_up.get_keyboards_display|upper}}</li>
    <li>{{line_up.get_bass_display|upper}}</li>
    <li>{{line_up.get_drums_display|upper}}</li>
</ul>
<img src="{{line_up.mark_foto.url}}" style="max-width: 1000px" alt="Deep Purple">
{% endfor %}

{% endblock %}

welcome/templates/welcome/navbar_welcome.html
<nav>
    <ul>
        <li><a href="{% url 'mp' %}">Home</a></li>
        <li><a href="{% url 'bnd' %}">The Band</a></li>
        <li><a href="{% url 'dsc' %}">Discography</a></li>
        <li><a href="{% url 'bio' %}">Bio</a></li>
        <li><a href="{% url 'gallery' %}">Gallery</a></li>
        <li><a href="https://deeppurple.com/">Official Web-Site</a></li>
        <li><a href="{% url 'contacts' %}">Contacts</a></li>
    </ul>
</nav>

welcome/templates/welcome/welcome.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'welcome/css/welcome.css' %}">
{% endblock %}

{% block title %} Deep Purple {% endblock %}

{% block content %}

{% include 'welcome/navbar_welcome.html' %}
<a href="{% url 'mp' %}">
    <img src="{% static 'welcome/img/welcome.png'%}" width="600" height="260">
</a>
<div class="footer">
    Fanpage by <a href="https://github.com/PavelCyargeenka">Pavel Cyargeenka</a>
</div>


{% endblock %}